//go:build !ignore_autogenerated

/*
Copyright 2024 Karel Van Hecke

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Auth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthList) DeepCopyInto(out *AuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Auth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthList.
func (in *AuthList) DeepCopy() *AuthList {
	if in == nil {
		return nil
	}
	out := new(AuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(bool)
		**out = **in
	}
	if in.Ca != nil {
		in, out := &in.Ca, &out.Ca
		*out = new(string)
		**out = **in
	}
	if in.KnownHosts != nil {
		in, out := &in.KnownHosts, &out.KnownHosts
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthStatus) DeepCopyInto(out *AuthStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthStatus.
func (in *AuthStatus) DeepCopy() *AuthStatus {
	if in == nil {
		return nil
	}
	out := new(AuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInit) DeepCopyInto(out *CloudInit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInit.
func (in *CloudInit) DeepCopy() *CloudInit {
	if in == nil {
		return nil
	}
	out := new(CloudInit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudInit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitBond) DeepCopyInto(out *CloudInitBond) {
	*out = *in
	in.CloudInitNetworkProperties.DeepCopyInto(&out.CloudInitNetworkProperties)
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(CloudInitBondParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitBond.
func (in *CloudInitBond) DeepCopy() *CloudInitBond {
	if in == nil {
		return nil
	}
	out := new(CloudInitBond)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitBondParameters) DeepCopyInto(out *CloudInitBondParameters) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.LACPRate != nil {
		in, out := &in.LACPRate, &out.LACPRate
		*out = new(string)
		**out = **in
	}
	if in.MIIMonitorInterval != nil {
		in, out := &in.MIIMonitorInterval, &out.MIIMonitorInterval
		*out = new(int32)
		**out = **in
	}
	if in.MinLinks != nil {
		in, out := &in.MinLinks, &out.MinLinks
		*out = new(int32)
		**out = **in
	}
	if in.TransmitHashPolicy != nil {
		in, out := &in.TransmitHashPolicy, &out.TransmitHashPolicy
		*out = new(string)
		**out = **in
	}
	if in.ADSelect != nil {
		in, out := &in.ADSelect, &out.ADSelect
		*out = new(string)
		**out = **in
	}
	if in.AllSlavesActive != nil {
		in, out := &in.AllSlavesActive, &out.AllSlavesActive
		*out = new(bool)
		**out = **in
	}
	if in.ARPInterval != nil {
		in, out := &in.ARPInterval, &out.ARPInterval
		*out = new(int32)
		**out = **in
	}
	if in.ARPIPTargets != nil {
		in, out := &in.ARPIPTargets, &out.ARPIPTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ARPValidate != nil {
		in, out := &in.ARPValidate, &out.ARPValidate
		*out = new(string)
		**out = **in
	}
	if in.ARPAllTargets != nil {
		in, out := &in.ARPAllTargets, &out.ARPAllTargets
		*out = new(string)
		**out = **in
	}
	if in.UpDelay != nil {
		in, out := &in.UpDelay, &out.UpDelay
		*out = new(int32)
		**out = **in
	}
	if in.DownDelay != nil {
		in, out := &in.DownDelay, &out.DownDelay
		*out = new(int32)
		**out = **in
	}
	if in.FailOverMACPolicy != nil {
		in, out := &in.FailOverMACPolicy, &out.FailOverMACPolicy
		*out = new(string)
		**out = **in
	}
	if in.GratuitousARP != nil {
		in, out := &in.GratuitousARP, &out.GratuitousARP
		*out = new(int32)
		**out = **in
	}
	if in.PacketsPerSlave != nil {
		in, out := &in.PacketsPerSlave, &out.PacketsPerSlave
		*out = new(int32)
		**out = **in
	}
	if in.PrimaryReselectPolicy != nil {
		in, out := &in.PrimaryReselectPolicy, &out.PrimaryReselectPolicy
		*out = new(string)
		**out = **in
	}
	if in.LearnPacketInterval != nil {
		in, out := &in.LearnPacketInterval, &out.LearnPacketInterval
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitBondParameters.
func (in *CloudInitBondParameters) DeepCopy() *CloudInitBondParameters {
	if in == nil {
		return nil
	}
	out := new(CloudInitBondParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitBridge) DeepCopyInto(out *CloudInitBridge) {
	*out = *in
	in.CloudInitNetworkProperties.DeepCopyInto(&out.CloudInitNetworkProperties)
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(CloudInitBridgeParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitBridge.
func (in *CloudInitBridge) DeepCopy() *CloudInitBridge {
	if in == nil {
		return nil
	}
	out := new(CloudInitBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitBridgeParameters) DeepCopyInto(out *CloudInitBridgeParameters) {
	*out = *in
	if in.AgeingTime != nil {
		in, out := &in.AgeingTime, &out.AgeingTime
		*out = new(int32)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.ForwardDelay != nil {
		in, out := &in.ForwardDelay, &out.ForwardDelay
		*out = new(int32)
		**out = **in
	}
	if in.HelloTime != nil {
		in, out := &in.HelloTime, &out.HelloTime
		*out = new(int32)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(int32)
		**out = **in
	}
	if in.PathCost != nil {
		in, out := &in.PathCost, &out.PathCost
		*out = new(int32)
		**out = **in
	}
	if in.STP != nil {
		in, out := &in.STP, &out.STP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitBridgeParameters.
func (in *CloudInitBridgeParameters) DeepCopy() *CloudInitBridgeParameters {
	if in == nil {
		return nil
	}
	out := new(CloudInitBridgeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitCACerts) DeepCopyInto(out *CloudInitCACerts) {
	*out = *in
	if in.RemoveDefaults != nil {
		in, out := &in.RemoveDefaults, &out.RemoveDefaults
		*out = new(bool)
		**out = **in
	}
	if in.Trusted != nil {
		in, out := &in.Trusted, &out.Trusted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitCACerts.
func (in *CloudInitCACerts) DeepCopy() *CloudInitCACerts {
	if in == nil {
		return nil
	}
	out := new(CloudInitCACerts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitCloudConfig) DeepCopyInto(out *CloudInitCloudConfig) {
	*out = *in
	if in.BootCMD != nil {
		in, out := &in.BootCMD, &out.BootCMD
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(CloudInitUser)
		(*in).DeepCopyInto(*out)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]CloudInitUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WriteFiles != nil {
		in, out := &in.WriteFiles, &out.WriteFiles
		*out = make([]CloudInitWriteFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RunCMD != nil {
		in, out := &in.RunCMD, &out.RunCMD
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Growpart != nil {
		in, out := &in.Growpart, &out.Growpart
		*out = new(CloudInitGrowpart)
		(*in).DeepCopyInto(*out)
	}
	if in.Mounts != nil {
		in, out := &in.Mounts, &out.Mounts
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.MountDefaultFields != nil {
		in, out := &in.MountDefaultFields, &out.MountDefaultFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Swap != nil {
		in, out := &in.Swap, &out.Swap
		*out = new(CloudInitMountSwap)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceAliases != nil {
		in, out := &in.DeviceAliases, &out.DeviceAliases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DiskSetup != nil {
		in, out := &in.DiskSetup, &out.DiskSetup
		*out = make(map[string]CloudInitDisk, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.FSSetup != nil {
		in, out := &in.FSSetup, &out.FSSetup
		*out = make([]CloudInitFS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CACerts != nil {
		in, out := &in.CACerts, &out.CACerts
		*out = new(CloudInitCACerts)
		(*in).DeepCopyInto(*out)
	}
	if in.PreserveHostname != nil {
		in, out := &in.PreserveHostname, &out.PreserveHostname
		*out = new(bool)
		**out = **in
	}
	if in.PreferFQDNOverHostname != nil {
		in, out := &in.PreferFQDNOverHostname, &out.PreferFQDNOverHostname
		*out = new(bool)
		**out = **in
	}
	if in.CreateHostnameFile != nil {
		in, out := &in.CreateHostnameFile, &out.CreateHostnameFile
		*out = new(bool)
		**out = **in
	}
	if in.FQDN != nil {
		in, out := &in.FQDN, &out.FQDN
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.NTP != nil {
		in, out := &in.NTP, &out.NTP
		*out = new(CloudInitNTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Locale != nil {
		in, out := &in.Locale, &out.Locale
		*out = new(string)
		**out = **in
	}
	if in.LocaleConfigfile != nil {
		in, out := &in.LocaleConfigfile, &out.LocaleConfigfile
		*out = new(string)
		**out = **in
	}
	if in.Keyboard != nil {
		in, out := &in.Keyboard, &out.Keyboard
		*out = new(CloudInitKeyboard)
		(*in).DeepCopyInto(*out)
	}
	if in.PhoneHome != nil {
		in, out := &in.PhoneHome, &out.PhoneHome
		*out = new(CloudInitPhoneHome)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitCloudConfig.
func (in *CloudInitCloudConfig) DeepCopy() *CloudInitCloudConfig {
	if in == nil {
		return nil
	}
	out := new(CloudInitCloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitDHCPOverrides) DeepCopyInto(out *CloudInitDHCPOverrides) {
	*out = *in
	if in.UseDNS != nil {
		in, out := &in.UseDNS, &out.UseDNS
		*out = new(bool)
		**out = **in
	}
	if in.UseNTP != nil {
		in, out := &in.UseNTP, &out.UseNTP
		*out = new(bool)
		**out = **in
	}
	if in.SendHostName != nil {
		in, out := &in.SendHostName, &out.SendHostName
		*out = new(bool)
		**out = **in
	}
	if in.UseMTU != nil {
		in, out := &in.UseMTU, &out.UseMTU
		*out = new(bool)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.UseRoutes != nil {
		in, out := &in.UseRoutes, &out.UseRoutes
		*out = new(bool)
		**out = **in
	}
	if in.RouteMetric != nil {
		in, out := &in.RouteMetric, &out.RouteMetric
		*out = new(int32)
		**out = **in
	}
	if in.UseDomains != nil {
		in, out := &in.UseDomains, &out.UseDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitDHCPOverrides.
func (in *CloudInitDHCPOverrides) DeepCopy() *CloudInitDHCPOverrides {
	if in == nil {
		return nil
	}
	out := new(CloudInitDHCPOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitDisk) DeepCopyInto(out *CloudInitDisk) {
	*out = *in
	if in.TableType != nil {
		in, out := &in.TableType, &out.TableType
		*out = new(string)
		**out = **in
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitDisk.
func (in *CloudInitDisk) DeepCopy() *CloudInitDisk {
	if in == nil {
		return nil
	}
	out := new(CloudInitDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitEthernet) DeepCopyInto(out *CloudInitEthernet) {
	*out = *in
	in.CloudInitPhysicalProperties.DeepCopyInto(&out.CloudInitPhysicalProperties)
	in.CloudInitNetworkProperties.DeepCopyInto(&out.CloudInitNetworkProperties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitEthernet.
func (in *CloudInitEthernet) DeepCopy() *CloudInitEthernet {
	if in == nil {
		return nil
	}
	out := new(CloudInitEthernet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitFS) DeepCopyInto(out *CloudInitFS) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Partitions != nil {
		in, out := &in.Partitions, &out.Partitions
		*out = new(string)
		**out = **in
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceFS != nil {
		in, out := &in.ReplaceFS, &out.ReplaceFS
		*out = new(string)
		**out = **in
	}
	if in.ExtraOpts != nil {
		in, out := &in.ExtraOpts, &out.ExtraOpts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CMD != nil {
		in, out := &in.CMD, &out.CMD
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitFS.
func (in *CloudInitFS) DeepCopy() *CloudInitFS {
	if in == nil {
		return nil
	}
	out := new(CloudInitFS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitGrowpart) DeepCopyInto(out *CloudInitGrowpart) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreGrowrootDisabled != nil {
		in, out := &in.IgnoreGrowrootDisabled, &out.IgnoreGrowrootDisabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitGrowpart.
func (in *CloudInitGrowpart) DeepCopy() *CloudInitGrowpart {
	if in == nil {
		return nil
	}
	out := new(CloudInitGrowpart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitKeyboard) DeepCopyInto(out *CloudInitKeyboard) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Variant != nil {
		in, out := &in.Variant, &out.Variant
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitKeyboard.
func (in *CloudInitKeyboard) DeepCopy() *CloudInitKeyboard {
	if in == nil {
		return nil
	}
	out := new(CloudInitKeyboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitList) DeepCopyInto(out *CloudInitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudInit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitList.
func (in *CloudInitList) DeepCopy() *CloudInitList {
	if in == nil {
		return nil
	}
	out := new(CloudInitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudInitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitMatch) DeepCopyInto(out *CloudInitMatch) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
	if in.Driver != nil {
		in, out := &in.Driver, &out.Driver
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitMatch.
func (in *CloudInitMatch) DeepCopy() *CloudInitMatch {
	if in == nil {
		return nil
	}
	out := new(CloudInitMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitMetadata) DeepCopyInto(out *CloudInitMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitMetadata.
func (in *CloudInitMetadata) DeepCopy() *CloudInitMetadata {
	if in == nil {
		return nil
	}
	out := new(CloudInitMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitMountSwap) DeepCopyInto(out *CloudInitMountSwap) {
	*out = *in
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitMountSwap.
func (in *CloudInitMountSwap) DeepCopy() *CloudInitMountSwap {
	if in == nil {
		return nil
	}
	out := new(CloudInitMountSwap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitNTP) DeepCopyInto(out *CloudInitNTP) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NTPClient != nil {
		in, out := &in.NTPClient, &out.NTPClient
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(CloudInitNTPConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitNTP.
func (in *CloudInitNTP) DeepCopy() *CloudInitNTP {
	if in == nil {
		return nil
	}
	out := new(CloudInitNTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitNTPConfig) DeepCopyInto(out *CloudInitNTPConfig) {
	*out = *in
	if in.ConfPath != nil {
		in, out := &in.ConfPath, &out.ConfPath
		*out = new(string)
		**out = **in
	}
	if in.CheckEXE != nil {
		in, out := &in.CheckEXE, &out.CheckEXE
		*out = new(string)
		**out = **in
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitNTPConfig.
func (in *CloudInitNTPConfig) DeepCopy() *CloudInitNTPConfig {
	if in == nil {
		return nil
	}
	out := new(CloudInitNTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitNameservers) DeepCopyInto(out *CloudInitNameservers) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitNameservers.
func (in *CloudInitNameservers) DeepCopy() *CloudInitNameservers {
	if in == nil {
		return nil
	}
	out := new(CloudInitNameservers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitNetworkConfig) DeepCopyInto(out *CloudInitNetworkConfig) {
	*out = *in
	if in.Ethernets != nil {
		in, out := &in.Ethernets, &out.Ethernets
		*out = make(map[string]CloudInitEthernet, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Bonds != nil {
		in, out := &in.Bonds, &out.Bonds
		*out = make(map[string]CloudInitBond, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Bridges != nil {
		in, out := &in.Bridges, &out.Bridges
		*out = make(map[string]CloudInitBridge, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.VLANs != nil {
		in, out := &in.VLANs, &out.VLANs
		*out = make(map[string]CloudInitVLAN, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitNetworkConfig.
func (in *CloudInitNetworkConfig) DeepCopy() *CloudInitNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(CloudInitNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitNetworkProperties) DeepCopyInto(out *CloudInitNetworkProperties) {
	*out = *in
	if in.Renderer != nil {
		in, out := &in.Renderer, &out.Renderer
		*out = new(string)
		**out = **in
	}
	if in.DHCP4 != nil {
		in, out := &in.DHCP4, &out.DHCP4
		*out = new(bool)
		**out = **in
	}
	if in.DHCP6 != nil {
		in, out := &in.DHCP6, &out.DHCP6
		*out = new(bool)
		**out = **in
	}
	if in.DHCP4Overrides != nil {
		in, out := &in.DHCP4Overrides, &out.DHCP4Overrides
		*out = new(CloudInitDHCPOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.DHCP6Overrides != nil {
		in, out := &in.DHCP6Overrides, &out.DHCP6Overrides
		*out = new(CloudInitDHCPOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int32)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = new(CloudInitNameservers)
		(*in).DeepCopyInto(*out)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]CloudInitRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NetplanPassthrough.DeepCopyInto(&out.NetplanPassthrough)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitNetworkProperties.
func (in *CloudInitNetworkProperties) DeepCopy() *CloudInitNetworkProperties {
	if in == nil {
		return nil
	}
	out := new(CloudInitNetworkProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitPhoneHome) DeepCopyInto(out *CloudInitPhoneHome) {
	*out = *in
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tries != nil {
		in, out := &in.Tries, &out.Tries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitPhoneHome.
func (in *CloudInitPhoneHome) DeepCopy() *CloudInitPhoneHome {
	if in == nil {
		return nil
	}
	out := new(CloudInitPhoneHome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitPhysicalProperties) DeepCopyInto(out *CloudInitPhysicalProperties) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(CloudInitMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.SetName != nil {
		in, out := &in.SetName, &out.SetName
		*out = new(string)
		**out = **in
	}
	if in.WakeOnLAN != nil {
		in, out := &in.WakeOnLAN, &out.WakeOnLAN
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitPhysicalProperties.
func (in *CloudInitPhysicalProperties) DeepCopy() *CloudInitPhysicalProperties {
	if in == nil {
		return nil
	}
	out := new(CloudInitPhysicalProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitRoute) DeepCopyInto(out *CloudInitRoute) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitRoute.
func (in *CloudInitRoute) DeepCopy() *CloudInitRoute {
	if in == nil {
		return nil
	}
	out := new(CloudInitRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitSpec) DeepCopyInto(out *CloudInitSpec) {
	*out = *in
	out.PoolRef = in.PoolRef
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(CloudInitMetadata)
		**out = **in
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(CloudInitCloudConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VendorData != nil {
		in, out := &in.VendorData, &out.VendorData
		*out = new(CloudInitCloudConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkConfig != nil {
		in, out := &in.NetworkConfig, &out.NetworkConfig
		*out = new(CloudInitNetworkConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitSpec.
func (in *CloudInitSpec) DeepCopy() *CloudInitSpec {
	if in == nil {
		return nil
	}
	out := new(CloudInitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitStatus) DeepCopyInto(out *CloudInitStatus) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(VolumeIdentifier)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitStatus.
func (in *CloudInitStatus) DeepCopy() *CloudInitStatus {
	if in == nil {
		return nil
	}
	out := new(CloudInitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitUser) DeepCopyInto(out *CloudInitUser) {
	*out = *in
	if in.Doas != nil {
		in, out := &in.Doas, &out.Doas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExpireDate != nil {
		in, out := &in.ExpireDate, &out.ExpireDate
		*out = new(string)
		**out = **in
	}
	if in.Gecos != nil {
		in, out := &in.Gecos, &out.Gecos
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = new(string)
		**out = **in
	}
	if in.HomeDir != nil {
		in, out := &in.HomeDir, &out.HomeDir
		*out = new(string)
		**out = **in
	}
	if in.Intactive != nil {
		in, out := &in.Intactive, &out.Intactive
		*out = new(string)
		**out = **in
	}
	if in.LockPasswd != nil {
		in, out := &in.LockPasswd, &out.LockPasswd
		*out = new(bool)
		**out = **in
	}
	if in.NoCreateHome != nil {
		in, out := &in.NoCreateHome, &out.NoCreateHome
		*out = new(bool)
		**out = **in
	}
	if in.NoLogInit != nil {
		in, out := &in.NoLogInit, &out.NoLogInit
		*out = new(bool)
		**out = **in
	}
	if in.NoUserGroup != nil {
		in, out := &in.NoUserGroup, &out.NoUserGroup
		*out = new(bool)
		**out = **in
	}
	if in.Passwd != nil {
		in, out := &in.Passwd, &out.Passwd
		*out = new(string)
		**out = **in
	}
	if in.HashedPasswd != nil {
		in, out := &in.HashedPasswd, &out.HashedPasswd
		*out = new(string)
		**out = **in
	}
	if in.PlaintextPasswd != nil {
		in, out := &in.PlaintextPasswd, &out.PlaintextPasswd
		*out = new(string)
		**out = **in
	}
	if in.CreateGroups != nil {
		in, out := &in.CreateGroups, &out.CreateGroups
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryGroup != nil {
		in, out := &in.PrimaryGroup, &out.PrimaryGroup
		*out = new(string)
		**out = **in
	}
	if in.SELinuxUser != nil {
		in, out := &in.SELinuxUser, &out.SELinuxUser
		*out = new(string)
		**out = **in
	}
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = new(string)
		**out = **in
	}
	if in.SnapUser != nil {
		in, out := &in.SnapUser, &out.SnapUser
		*out = new(string)
		**out = **in
	}
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SSHImportID != nil {
		in, out := &in.SSHImportID, &out.SSHImportID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SSHRedirectUser != nil {
		in, out := &in.SSHRedirectUser, &out.SSHRedirectUser
		*out = new(bool)
		**out = **in
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(bool)
		**out = **in
	}
	if in.Sudo != nil {
		in, out := &in.Sudo, &out.Sudo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitUser.
func (in *CloudInitUser) DeepCopy() *CloudInitUser {
	if in == nil {
		return nil
	}
	out := new(CloudInitUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitVLAN) DeepCopyInto(out *CloudInitVLAN) {
	*out = *in
	in.CloudInitNetworkProperties.DeepCopyInto(&out.CloudInitNetworkProperties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitVLAN.
func (in *CloudInitVLAN) DeepCopy() *CloudInitVLAN {
	if in == nil {
		return nil
	}
	out := new(CloudInitVLAN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitWriteFile) DeepCopyInto(out *CloudInitWriteFile) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(CloudInitWriteFileSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(string)
		**out = **in
	}
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(string)
		**out = **in
	}
	if in.Append != nil {
		in, out := &in.Append, &out.Append
		*out = new(bool)
		**out = **in
	}
	if in.Defer != nil {
		in, out := &in.Defer, &out.Defer
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitWriteFile.
func (in *CloudInitWriteFile) DeepCopy() *CloudInitWriteFile {
	if in == nil {
		return nil
	}
	out := new(CloudInitWriteFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitWriteFileSource) DeepCopyInto(out *CloudInitWriteFileSource) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitWriteFileSource.
func (in *CloudInitWriteFileSource) DeepCopy() *CloudInitWriteFileSource {
	if in == nil {
		return nil
	}
	out := new(CloudInitWriteFileSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Host) DeepCopyInto(out *Host) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Host.
func (in *Host) DeepCopy() *Host {
	if in == nil {
		return nil
	}
	out := new(Host)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Host) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCapacity) DeepCopyInto(out *HostCapacity) {
	*out = *in
	out.Memory = in.Memory
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCapacity.
func (in *HostCapacity) DeepCopy() *HostCapacity {
	if in == nil {
		return nil
	}
	out := new(HostCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostList) DeepCopyInto(out *HostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Host, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostList.
func (in *HostList) DeepCopy() *HostList {
	if in == nil {
		return nil
	}
	out := new(HostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMemory) DeepCopyInto(out *HostMemory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMemory.
func (in *HostMemory) DeepCopy() *HostMemory {
	if in == nil {
		return nil
	}
	out := new(HostMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSpec) DeepCopyInto(out *HostSpec) {
	*out = *in
	out.AuthRef = in.AuthRef
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSpec.
func (in *HostSpec) DeepCopy() *HostSpec {
	if in == nil {
		return nil
	}
	out := new(HostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostStatus) DeepCopyInto(out *HostStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(HostCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostStatus.
func (in *HostStatus) DeepCopy() *HostStatus {
	if in == nil {
		return nil
	}
	out := new(HostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibvirtIdentifier) DeepCopyInto(out *LibvirtIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibvirtIdentifier.
func (in *LibvirtIdentifier) DeepCopy() *LibvirtIdentifier {
	if in == nil {
		return nil
	}
	out := new(LibvirtIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibvirtIdentifierWithUUID) DeepCopyInto(out *LibvirtIdentifierWithUUID) {
	*out = *in
	out.LibvirtIdentifier = in.LibvirtIdentifier
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibvirtIdentifierWithUUID.
func (in *LibvirtIdentifierWithUUID) DeepCopy() *LibvirtIdentifierWithUUID {
	if in == nil {
		return nil
	}
	out := new(LibvirtIdentifierWithUUID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibvirtLookup) DeepCopyInto(out *LibvirtLookup) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	out.HostRef = in.HostRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibvirtLookup.
func (in *LibvirtLookup) DeepCopy() *LibvirtLookup {
	if in == nil {
		return nil
	}
	out := new(LibvirtLookup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetplanPassthrough) DeepCopyInto(out *NetplanPassthrough) {
	*out = *in
	if in.AcceptRA != nil {
		in, out := &in.AcceptRA, &out.AcceptRA
		*out = new(bool)
		**out = **in
	}
	if in.RAOverrides != nil {
		in, out := &in.RAOverrides, &out.RAOverrides
		*out = new(NetplanRAOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetplanPassthrough.
func (in *NetplanPassthrough) DeepCopy() *NetplanPassthrough {
	if in == nil {
		return nil
	}
	out := new(NetplanPassthrough)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetplanRAOverrides) DeepCopyInto(out *NetplanRAOverrides) {
	*out = *in
	if in.UseDNS != nil {
		in, out := &in.UseDNS, &out.UseDNS
		*out = new(bool)
		**out = **in
	}
	if in.UseDomains != nil {
		in, out := &in.UseDomains, &out.UseDomains
		*out = new(string)
		**out = **in
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetplanRAOverrides.
func (in *NetplanRAOverrides) DeepCopy() *NetplanRAOverrides {
	if in == nil {
		return nil
	}
	out := new(NetplanRAOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Network) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkList) DeepCopyInto(out *NetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Network, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkList.
func (in *NetworkList) DeepCopy() *NetworkList {
	if in == nil {
		return nil
	}
	out := new(NetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	in.LibvirtLookup.DeepCopyInto(&out.LibvirtLookup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(LibvirtIdentifierWithUUID)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDevice) DeepCopyInto(out *PCIDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDevice.
func (in *PCIDevice) DeepCopy() *PCIDevice {
	if in == nil {
		return nil
	}
	out := new(PCIDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PCIDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDeviceAddress) DeepCopyInto(out *PCIDeviceAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDeviceAddress.
func (in *PCIDeviceAddress) DeepCopy() *PCIDeviceAddress {
	if in == nil {
		return nil
	}
	out := new(PCIDeviceAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDeviceList) DeepCopyInto(out *PCIDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PCIDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDeviceList.
func (in *PCIDeviceList) DeepCopy() *PCIDeviceList {
	if in == nil {
		return nil
	}
	out := new(PCIDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PCIDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDeviceSpec) DeepCopyInto(out *PCIDeviceSpec) {
	*out = *in
	out.HostRef = in.HostRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDeviceSpec.
func (in *PCIDeviceSpec) DeepCopy() *PCIDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(PCIDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDeviceStatus) DeepCopyInto(out *PCIDeviceStatus) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(LibvirtIdentifier)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(PCIDeviceAddress)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDeviceStatus.
func (in *PCIDeviceStatus) DeepCopy() *PCIDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(PCIDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool) DeepCopyInto(out *Pool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool.
func (in *Pool) DeepCopy() *Pool {
	if in == nil {
		return nil
	}
	out := new(Pool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolCapacity) DeepCopyInto(out *PoolCapacity) {
	*out = *in
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolCapacity.
func (in *PoolCapacity) DeepCopy() *PoolCapacity {
	if in == nil {
		return nil
	}
	out := new(PoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolList) DeepCopyInto(out *PoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolList.
func (in *PoolList) DeepCopy() *PoolList {
	if in == nil {
		return nil
	}
	out := new(PoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSpec) DeepCopyInto(out *PoolSpec) {
	*out = *in
	in.LibvirtLookup.DeepCopyInto(&out.LibvirtLookup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSpec.
func (in *PoolSpec) DeepCopy() *PoolSpec {
	if in == nil {
		return nil
	}
	out := new(PoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolStatus) DeepCopyInto(out *PoolStatus) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(LibvirtIdentifierWithUUID)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(PoolCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolStatus.
func (in *PoolStatus) DeepCopy() *PoolStatus {
	if in == nil {
		return nil
	}
	out := new(PoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Volume) DeepCopyInto(out *Volume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volume.
func (in *Volume) DeepCopy() *Volume {
	if in == nil {
		return nil
	}
	out := new(Volume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Volume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeIdentifier) DeepCopyInto(out *VolumeIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeIdentifier.
func (in *VolumeIdentifier) DeepCopy() *VolumeIdentifier {
	if in == nil {
		return nil
	}
	out := new(VolumeIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeList) DeepCopyInto(out *VolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeList.
func (in *VolumeList) DeepCopy() *VolumeList {
	if in == nil {
		return nil
	}
	out := new(VolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSize) DeepCopyInto(out *VolumeSize) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSize.
func (in *VolumeSize) DeepCopy() *VolumeSize {
	if in == nil {
		return nil
	}
	out := new(VolumeSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSource) DeepCopyInto(out *VolumeSource) {
	*out = *in
	if in.Checksum != nil {
		in, out := &in.Checksum, &out.Checksum
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSource.
func (in *VolumeSource) DeepCopy() *VolumeSource {
	if in == nil {
		return nil
	}
	out := new(VolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	out.Size = in.Size
	out.PoolRef = in.PoolRef
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(VolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.BackingStoreRef != nil {
		in, out := &in.BackingStoreRef, &out.BackingStoreRef
		*out = new(ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStatus) DeepCopyInto(out *VolumeStatus) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(VolumeIdentifier)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStatus.
func (in *VolumeStatus) DeepCopy() *VolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStatus)
	in.DeepCopyInto(out)
	return out
}
