---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libvirt-operator
  namespace: libvirt-operator
subjects:
- kind: ServiceAccount
  name: libvirt-operator
  namespace: libvirt-operator
roleRef:
  kind: Role
  name: libvirt-operator
  apiGroup: rbac.authorization.k8s.io
