---
name: Container image

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      push:
        description: Push to registry
        type: boolean
        default: false
        required: false
      platforms:
        description: Platforms
        type: string
        default: linux/amd64
        required: false
    outputs:
      digest:
        description: Image digest
        value: ${{ jobs.build.outputs.digest }}

env:
  # renovate: datasource=github-releases depName=docker/buildx versioning=semver
  BUILDX_VERSION: 'v0.20.0'

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup qemu
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0

      - name: Setup buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
        with:
          version: ${{ env.BUILDX_VERSION }}

      - name: Login to GitHub registry
        if: ${{ github.event_name != 'pull_request' && inputs.push || false }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: |
            ghcr.io/karelvanhecke/libvirt-operator
          tags: |
            type=semver,pattern={{version}},priority=990,prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref_name, 'v0.') }},prefix=v
            type=ref,event=pr
            type=sha,format=long,enable=${{ !startsWith(github.ref, 'refs/tags/') }}
            type=edge,enable=${{ startsWith(github.ref, 'refs/heads/') }},priority=90

      - name: Build
        id: build
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
        with:
          context: .
          platforms: ${{ github.event_name != 'pull_request' && inputs.platforms || 'linux/amd64' }}
          push: ${{ github.event_name != 'pull_request' && inputs.push || false }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
          provenance: false
