---
name: Operator deployment

on:
  pull_request:
    branches:
      - main

env:
  # renovate: datasource=golang-version depName=go
  GO_VERSION: '1.24.3'
  # renovate: datasource=github-releases depName=docker/buildx versioning=semver
  BUILDX_VERSION: 'v0.21.3'

jobs:
  test-deploy-to-kind:
    name: Test deploy to Kind
    env:
      VERSION: pr-${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          version: ${{ env.BUILDX_VERSION }}

      - name: Install kind
        run: make install-kind

      - name: Install kubectl
        run: make install-kubectl

      - name: Create kind cluster
        run: make create-kind-cluster

      - name: Build container
        run: make build-container

      - name: Deploy to kind cluster
        run: make deploy-to-kind-cluster
