---
name: Operator deployment

on:
  pull_request:
    branches:
      - main

env:
  # renovate: datasource=golang-version depName=go
  GO_VERSION: '1.23.5'
  # renovate: datasource=github-releases depName=docker/buildx versioning=semver
  BUILDX_VERSION: 'v0.19.3'

jobs:
  test-deploy-to-kind:
    name: Test deploy to Kind
    env:
      VERSION: pr-${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
        with:
          version: ${{ env.BUILDX_VERSION }}

      - name: Install kind
        run: make install-kind

      - name: Install kubectl
        run: make install-kubectl

      - name: Create kind cluster
        run: make create-kind-cluster

      - name: Build container
        run: make build-container

      - name: Deploy to kind cluster
        run: make deploy-to-kind-cluster
