---
name: OSV

on:
  schedule:
    - cron: '15 1 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  scan:
    name: Scan
    if: ${{ github.event_name != 'pull_request' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@6fc714450122bda9d00e4ad5d639ad6a39eedb1f # v2.0.1
    with:
      scan-args: |-
        -r
        --config=.github/osv.toml
        ./

  scan-pr:
    name: Scan PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@6fc714450122bda9d00e4ad5d639ad6a39eedb1f # v2.0.1
    with:
      scan-args: |-
        -r
        --config=.github/osv.toml
        ./
