---
name: OSV

on:
  schedule:
    - cron: '15 1 * * *'
  push:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  scan:
    name: Scan
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@764c91816374ff2d8fc2095dab36eecd42d61638 # v1.9.2
    with:
      scan-args: |-
        --skip-git=true # Skip commit scanning to focus on dependencies
        ./ # Start the scan from the root of the repository
