---
name: Release

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - '**/*.go'
      - 'Dockerfile'

permissions:
  packages: write
  id-token: write

env:
  # renovate: datasource=github-releases depName=sigstore/cosign versioning=semver
  COSIGN_VERSION: 'v2.4.3'

jobs:
  release:
    name: Release container image
    permissions:
      packages: write
    uses: ./.github/workflows/container-image.yaml
    with:
      push: true
      platforms: linux/amd64,linux/arm64

  sign:
    name: Sign container image
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Login to GitHub registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign with cosign
        run: cosign sign --yes ghcr.io/karelvanhecke/libvirt-operator@${{ needs.release.outputs.digest }}
