---
name: Release

on:
  push:
    tags:
      - v*

permissions:
  packages: write
  id-token: write
  contents: read

env:
  # renovate: datasource=github-releases depName=sigstore/cosign versioning=semver
  COSIGN_VERSION: 'v2.4.1'
  # renovate: datasource=github-releases depName=docker/buildx versioning=semver
  BUILDX_VERSION: 'v0.18.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup qemu
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Setup buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          version: ${{ env.BUILDX_VERSION }}

      - name: Setup cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Login to GitHub registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            ghcr.io/karelvanhecke/libvirt-operator

      - name: Build and push container
        id: build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: OPERATOR_VERSION=${{ github.ref_name }}

      - name: Sign container
        run: cosign sign --yes ghcr.io/karelvanhecke/libvirt-operator@${{ steps.build.outputs.digest }}
