---
name: Renovate config

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run config validator
        env:
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate versioning=semver
          RENOVATE_VERSION: 39.86.0@sha256:782e91ae22e25858409478c0a4cc1833a9b7ef11f82ea0140a6fee0436871f14
        run: >
          docker run --rm -v ./.github/renovate.json:/renovate.json
          --entrypoint renovate-config-validator
          ghcr.io/renovatebot/renovate:${RENOVATE_VERSION} /renovate.json
