---
name: Renovate config

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run config validator
        env:
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate versioning=semver
          RENOVATE_VERSION: 39.134.0@sha256:d72d0035beb9b7e0ef3dc7453637540169e37a3fa1e6f404fa5834e4284eb390
        run: >
          docker run --rm -v ./.github/renovate.json:/renovate.json
          --entrypoint renovate-config-validator
          ghcr.io/renovatebot/renovate:${RENOVATE_VERSION} /renovate.json
