---
name: Renovate config validator

on:
  pull_request:
    branches:
      - main
    paths:
      - renovate.json

jobs:
  renovate-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate renovate config
        run: docker run --rm --entrypoint renovate-config-validator -v ./renovate.json:/renovate.json ghcr.io/renovatebot/renovate:slim
