---
name: Renovate

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get app token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_ID }}
          private-key: ${{ secrets.RENOVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Renovate
        uses: renovatebot/github-action@28bcd5c4900a4353b5c9af9e1bd61dd6377f0f0d # v40.3.5
        with:
          configurationFile: .github/renovate.json
          renovate-version: 39.7.6@sha256:7113119d7ffc02815c54f4ddd64f3d7efb7dd80841d4ac9143d24189ec7cc387
          token: '${{ steps.app-token.outputs.token }}'
